BASE:
 test:
  url: "https://rrwapi.renren.com"
  url_person: "http://www.renren.com"
# log等级
  log_level: "debug"
# log扩展名
  log_extension: .log
#  excel文件名及sheet名

 excel:
  excel_name: "testdata.xls"
  sheet_by: 0