db_1:
 db_host: "127.0.0.1"
 db_user: "root"
 db_password: ""
 db_name: "mysql"
 db_charset: "utf-8"
 db_port: 3306


db_2:
 db_host: "127.0.0.2"
 db_user: "root"
 db_password: "root"
 db_name: "mysql"
 db_charset: "utf-8"
 db_port: "3306"


db_3:
 db_host: "127.0.0.3"
 db_user: "root"
 db_password: "root"
 db_name: "mysql"
 db_charset: "utf-8"
 db_port: "3306"